// Deterministic test configurations for 32 avatars
// This covers every single topType (32 distinct tops), other options rotated/distributed,
// and custom palette colors to verify custom registration.

export const CUSTOM_COLORS = [
  { palette: 'BACKDROP', name: 'CustomBackdropGreen', color: '#10B981' },
  { palette: 'SKIN', name: 'CustomSkinPurple', color: '#8B5CF6' },
  { palette: 'HAIR', name: 'CustomHairHotPink', color: '#FF1493' },
  { palette: 'FACIAL_HAIR', name: 'CustomFacialHairTeal', color: '#008080' },
  { palette: 'CLOTHES', name: 'CustomClotheOrange', color: '#FF4500' },
  { palette: 'HAT', name: 'CustomHatLime', color: '#00FF00' },
]

export interface AvatarConfig {
  id: string
  backdropType: string
  backdropColor: string
  topType: string
  accessoriesType: string
  hairColor: string
  hatColor: string
  facialHairType: string
  facialHairColor: string
  clotheType: string
  clotheColor: string
  graphicType: string
  eyeType: string
  eyebrowType: string
  mouthType: string
  skinColor: string
}

export const DEBUG_CONFIGS: AvatarConfig[] = [
  {
    id: 'avatar-1',
    backdropType: 'Circle',
    backdropColor: 'Blue01',
    topType: 'NoHair',
    accessoriesType: 'Blank',
    hairColor: 'Auburn',
    hatColor: 'Black',
    facialHairType: 'Blank',
    facialHairColor: 'Auburn',
    clotheType: 'BlazerShirt',
    clotheColor: 'Black',
    graphicType: 'Bat',
    eyeType: 'Close',
    eyebrowType: 'Angry',
    mouthType: 'Concerned',
    skinColor: 'Tanned',
  },
  {
    id: 'avatar-2',
    backdropType: 'Circle',
    backdropColor: 'Gray01',
    topType: 'Eyepatch',
    accessoriesType: 'Kurt',
    hairColor: 'Black',
    hatColor: 'Blue01',
    facialHairType: 'BeardMedium',
    facialHairColor: 'Black',
    clotheType: 'BlazerSweater',
    clotheColor: 'Blue01',
    graphicType: 'Cumbia',
    eyeType: 'Cry',
    eyebrowType: 'AngryNatural',
    mouthType: 'Default',
    skinColor: 'Yellow',
  },
  {
    id: 'avatar-3',
    backdropType: 'Circle',
    backdropColor: 'Gray01',
    topType: 'Hat',
    accessoriesType: 'Prescription01',
    hairColor: 'Blonde',
    hatColor: 'Blue02',
    facialHairType: 'BeardLight',
    facialHairColor: 'Blonde',
    clotheType: 'CollarSweater',
    clotheColor: 'Blue02',
    graphicType: 'Deer',
    eyeType: 'Default',
    eyebrowType: 'Default',
    mouthType: 'Disbelief',
    skinColor: 'Pale',
  },
  {
    id: 'avatar-4',
    backdropType: 'Circle',
    backdropColor: 'Gray01',
    topType: 'Hijab',
    accessoriesType: 'Prescription02',
    hairColor: 'BlondeGolden',
    hatColor: 'Blue03',
    facialHairType: 'BeardMajestic',
    facialHairColor: 'BlondeGolden',
    clotheType: 'GraphicShirt',
    clotheColor: 'Blue03',
    graphicType: 'Diamond',
    eyeType: 'Dizzy',
    eyebrowType: 'DefaultNatural',
    mouthType: 'Eating',
    skinColor: 'Light',
  },
  {
    id: 'avatar-5',
    backdropType: 'Circle',
    backdropColor: 'PastelBlue',
    topType: 'Turban',
    accessoriesType: 'Round',
    hairColor: 'Brown',
    hatColor: 'Gray01',
    facialHairType: 'MoustacheFancy',
    facialHairColor: 'Brown',
    clotheType: 'Hoodie',
    clotheColor: 'Gray01',
    graphicType: 'Hola',
    eyeType: 'EyeRoll',
    eyebrowType: 'FlatNatural',
    mouthType: 'Grimace',
    skinColor: 'Brown',
  },
  {
    id: 'avatar-6',
    backdropType: 'Circle',
    backdropColor: 'PastelBlue',
    topType: 'WinterHat1',
    accessoriesType: 'Sunglasses',
    hairColor: 'BrownDark',
    hatColor: 'Gray02',
    facialHairType: 'MoustacheMagnum',
    facialHairColor: 'BrownDark',
    clotheType: 'Overall',
    clotheColor: 'Gray02',
    graphicType: 'Pizza',
    eyeType: 'Happy',
    eyebrowType: 'FrownNatural',
    mouthType: 'Sad',
    skinColor: 'DarkBrown',
  },
  {
    id: 'avatar-7',
    backdropType: 'Circle',
    backdropColor: 'PastelBlue',
    topType: 'WinterHat2',
    accessoriesType: 'Wayfarers',
    hairColor: 'PastelPink',
    hatColor: 'Heather',
    facialHairType: 'Blank',
    facialHairColor: 'Platinum',
    clotheType: 'ShirtCrewNeck',
    clotheColor: 'Heather',
    graphicType: 'Resist',
    eyeType: 'Hearts',
    eyebrowType: 'RaisedExcited',
    mouthType: 'ScreamOpen',
    skinColor: 'Black',
  },
  {
    id: 'avatar-8',
    backdropType: 'Circle',
    backdropColor: 'PastelGreen',
    topType: 'WinterHat3',
    accessoriesType: 'Blank',
    hairColor: 'Blue',
    hatColor: 'PastelBlue',
    facialHairType: 'BeardMedium',
    facialHairColor: 'Red',
    clotheType: 'ShirtScoopNeck',
    clotheColor: 'PastelBlue',
    graphicType: 'Selena',
    eyeType: 'Side',
    eyebrowType: 'RaisedExcitedNatural',
    mouthType: 'Serious',
    skinColor: 'CustomSkinPurple',
  },
  {
    id: 'avatar-9',
    backdropType: 'Circle',
    backdropColor: 'PastelOrange',
    topType: 'WinterHat4',
    accessoriesType: 'Kurt',
    hairColor: 'Platinum',
    hatColor: 'PastelGreen',
    facialHairType: 'BeardLight',
    facialHairColor: 'SilverGray',
    clotheType: 'ShirtVNeck',
    clotheColor: 'PastelGreen',
    graphicType: 'Bear',
    eyeType: 'Squint',
    eyebrowType: 'SadConcerned',
    mouthType: 'Smile',
    skinColor: 'Tanned',
  },
  {
    id: 'avatar-10',
    backdropType: 'Circle',
    backdropColor: 'PastelYellow',
    topType: 'LongHairBigHair',
    accessoriesType: 'Prescription01',
    hairColor: 'Red',
    hatColor: 'PastelOrange',
    facialHairType: 'BeardMajestic',
    facialHairColor: 'CustomFacialHairTeal',
    clotheType: 'BlazerShirt',
    clotheColor: 'PastelOrange',
    graphicType: 'SkullOutline',
    eyeType: 'Surprised',
    eyebrowType: 'SadConcernedNatural',
    mouthType: 'Tongue',
    skinColor: 'Yellow',
  },
  {
    id: 'avatar-11',
    backdropType: 'Circle',
    backdropColor: 'PastelYellow',
    topType: 'LongHairBob',
    accessoriesType: 'Prescription02',
    hairColor: 'SilverGray',
    hatColor: 'PastelRed',
    facialHairType: 'MoustacheFancy',
    facialHairColor: 'Auburn',
    clotheType: 'BlazerSweater',
    clotheColor: 'PastelRed',
    graphicType: 'Skull',
    eyeType: 'Wink',
    eyebrowType: 'UnibrowNatural',
    mouthType: 'Twinkle',
    skinColor: 'Pale',
  },
  {
    id: 'avatar-12',
    backdropType: 'Circle',
    backdropColor: 'Red',
    topType: 'LongHairBun',
    accessoriesType: 'Round',
    hairColor: 'CustomHairHotPink',
    hatColor: 'PastelYellow',
    facialHairType: 'MoustacheMagnum',
    facialHairColor: 'Black',
    clotheType: 'CollarSweater',
    clotheColor: 'PastelYellow',
    graphicType: 'Bat',
    eyeType: 'WinkWacky',
    eyebrowType: 'UpDown',
    mouthType: 'Vomit',
    skinColor: 'Light',
  },
  {
    id: 'avatar-13',
    backdropType: 'Circle',
    backdropColor: 'White',
    topType: 'LongHairCurly',
    accessoriesType: 'Sunglasses',
    hairColor: 'Auburn',
    hatColor: 'Pink',
    facialHairType: 'Blank',
    facialHairColor: 'Blonde',
    clotheType: 'GraphicShirt',
    clotheColor: 'Pink',
    graphicType: 'Cumbia',
    eyeType: 'Close',
    eyebrowType: 'UpDownNatural',
    mouthType: 'Concerned',
    skinColor: 'Brown',
  },
  {
    id: 'avatar-14',
    backdropType: 'Circle',
    backdropColor: 'White',
    topType: 'LongHairCurvy',
    accessoriesType: 'Wayfarers',
    hairColor: 'Black',
    hatColor: 'Red',
    facialHairType: 'BeardMedium',
    facialHairColor: 'BlondeGolden',
    clotheType: 'Hoodie',
    clotheColor: 'Red',
    graphicType: 'Deer',
    eyeType: 'Cry',
    eyebrowType: 'Angry',
    mouthType: 'Default',
    skinColor: 'DarkBrown',
  },
  {
    id: 'avatar-15',
    backdropType: 'Circle',
    backdropColor: 'CustomBackdropGreen',
    topType: 'LongHairDreads',
    accessoriesType: 'Blank',
    hairColor: 'Blonde',
    hatColor: 'White',
    facialHairType: 'BeardLight',
    facialHairColor: 'Brown',
    clotheType: 'Overall',
    clotheColor: 'White',
    graphicType: 'Diamond',
    eyeType: 'Default',
    eyebrowType: 'AngryNatural',
    mouthType: 'Disbelief',
    skinColor: 'Black',
  },
  {
    id: 'avatar-16',
    backdropType: 'Circle',
    backdropColor: 'CustomBackdropGreen',
    topType: 'LongHairFrida',
    accessoriesType: 'Kurt',
    hairColor: 'BlondeGolden',
    hatColor: 'CustomHatLime',
    facialHairType: 'BeardMajestic',
    facialHairColor: 'BrownDark',
    clotheType: 'ShirtCrewNeck',
    clotheColor: 'CustomClotheOrange',
    graphicType: 'Hola',
    eyeType: 'Dizzy',
    eyebrowType: 'Default',
    mouthType: 'Eating',
    skinColor: 'Tanned',
  },
  {
    id: 'avatar-17',
    backdropType: 'None',
    backdropColor: 'Blue01',
    topType: 'LongHairFro',
    accessoriesType: 'Prescription01',
    hairColor: 'Brown',
    hatColor: 'Black',
    facialHairType: 'MoustacheFancy',
    facialHairColor: 'Platinum',
    clotheType: 'ShirtScoopNeck',
    clotheColor: 'Black',
    graphicType: 'Pizza',
    eyeType: 'EyeRoll',
    eyebrowType: 'DefaultNatural',
    mouthType: 'Grimace',
    skinColor: 'Yellow',
  },
  {
    id: 'avatar-18',
    backdropType: 'None',
    backdropColor: 'Gray01',
    topType: 'LongHairFroBand',
    accessoriesType: 'Prescription02',
    hairColor: 'BrownDark',
    hatColor: 'Blue01',
    facialHairType: 'MoustacheMagnum',
    facialHairColor: 'Red',
    clotheType: 'ShirtVNeck',
    clotheColor: 'Blue01',
    graphicType: 'Resist',
    eyeType: 'Happy',
    eyebrowType: 'FlatNatural',
    mouthType: 'Sad',
    skinColor: 'Pale',
  },
  {
    id: 'avatar-19',
    backdropType: 'None',
    backdropColor: 'Gray01',
    topType: 'LongHairNotTooLong',
    accessoriesType: 'Round',
    hairColor: 'PastelPink',
    hatColor: 'Blue02',
    facialHairType: 'Blank',
    facialHairColor: 'SilverGray',
    clotheType: 'BlazerShirt',
    clotheColor: 'Blue02',
    graphicType: 'Selena',
    eyeType: 'Hearts',
    eyebrowType: 'FrownNatural',
    mouthType: 'ScreamOpen',
    skinColor: 'Light',
  },
  {
    id: 'avatar-20',
    backdropType: 'None',
    backdropColor: 'Gray01',
    topType: 'LongHairShavedSides',
    accessoriesType: 'Sunglasses',
    hairColor: 'Blue',
    hatColor: 'Blue03',
    facialHairType: 'BeardMedium',
    facialHairColor: 'CustomFacialHairTeal',
    clotheType: 'BlazerSweater',
    clotheColor: 'Blue03',
    graphicType: 'Bear',
    eyeType: 'Side',
    eyebrowType: 'RaisedExcited',
    mouthType: 'Serious',
    skinColor: 'Brown',
  },
  {
    id: 'avatar-21',
    backdropType: 'None',
    backdropColor: 'PastelBlue',
    topType: 'LongHairMiaWallace',
    accessoriesType: 'Wayfarers',
    hairColor: 'Platinum',
    hatColor: 'Gray01',
    facialHairType: 'BeardLight',
    facialHairColor: 'Auburn',
    clotheType: 'CollarSweater',
    clotheColor: 'Gray01',
    graphicType: 'SkullOutline',
    eyeType: 'Squint',
    eyebrowType: 'RaisedExcitedNatural',
    mouthType: 'Smile',
    skinColor: 'DarkBrown',
  },
  {
    id: 'avatar-22',
    backdropType: 'None',
    backdropColor: 'PastelBlue',
    topType: 'LongHairStraight',
    accessoriesType: 'Blank',
    hairColor: 'Red',
    hatColor: 'Gray02',
    facialHairType: 'BeardMajestic',
    facialHairColor: 'Black',
    clotheType: 'GraphicShirt',
    clotheColor: 'Gray02',
    graphicType: 'Skull',
    eyeType: 'Surprised',
    eyebrowType: 'SadConcerned',
    mouthType: 'Tongue',
    skinColor: 'Black',
  },
  {
    id: 'avatar-23',
    backdropType: 'None',
    backdropColor: 'PastelBlue',
    topType: 'LongHairStraight2',
    accessoriesType: 'Kurt',
    hairColor: 'SilverGray',
    hatColor: 'Heather',
    facialHairType: 'MoustacheFancy',
    facialHairColor: 'Blonde',
    clotheType: 'Hoodie',
    clotheColor: 'Heather',
    graphicType: 'Bat',
    eyeType: 'Wink',
    eyebrowType: 'SadConcernedNatural',
    mouthType: 'Twinkle',
    skinColor: 'CustomSkinPurple',
  },
  {
    id: 'avatar-24',
    backdropType: 'None',
    backdropColor: 'PastelGreen',
    topType: 'LongHairStraightStrand',
    accessoriesType: 'Prescription01',
    hairColor: 'CustomHairHotPink',
    hatColor: 'PastelBlue',
    facialHairType: 'MoustacheMagnum',
    facialHairColor: 'BlondeGolden',
    clotheType: 'Overall',
    clotheColor: 'PastelBlue',
    graphicType: 'Cumbia',
    eyeType: 'WinkWacky',
    eyebrowType: 'UnibrowNatural',
    mouthType: 'Vomit',
    skinColor: 'Tanned',
  },
  {
    id: 'avatar-25',
    backdropType: 'None',
    backdropColor: 'PastelOrange',
    topType: 'ShortHairDreads01',
    accessoriesType: 'Prescription02',
    hairColor: 'Auburn',
    hatColor: 'PastelGreen',
    facialHairType: 'Blank',
    facialHairColor: 'Brown',
    clotheType: 'ShirtCrewNeck',
    clotheColor: 'PastelGreen',
    graphicType: 'Deer',
    eyeType: 'Close',
    eyebrowType: 'UpDown',
    mouthType: 'Concerned',
    skinColor: 'Yellow',
  },
  {
    id: 'avatar-26',
    backdropType: 'None',
    backdropColor: 'PastelRed',
    topType: 'ShortHairDreads02',
    accessoriesType: 'Round',
    hairColor: 'Black',
    hatColor: 'PastelOrange',
    facialHairType: 'BeardMedium',
    facialHairColor: 'BrownDark',
    clotheType: 'ShirtScoopNeck',
    clotheColor: 'PastelOrange',
    graphicType: 'Diamond',
    eyeType: 'Cry',
    eyebrowType: 'UpDownNatural',
    mouthType: 'Default',
    skinColor: 'Pale',
  },
  {
    id: 'avatar-27',
    backdropType: 'None',
    backdropColor: 'Pink',
    topType: 'ShortHairFrizzle',
    accessoriesType: 'Sunglasses',
    hairColor: 'Blonde',
    hatColor: 'PastelRed',
    facialHairType: 'BeardLight',
    facialHairColor: 'Platinum',
    clotheType: 'ShirtVNeck',
    clotheColor: 'PastelRed',
    graphicType: 'Hola',
    eyeType: 'Default',
    eyebrowType: 'Angry',
    mouthType: 'Disbelief',
    skinColor: 'Light',
  },
  {
    id: 'avatar-28',
    backdropType: 'None',
    backdropColor: 'Pink',
    topType: 'ShortHairShaggy',
    accessoriesType: 'Wayfarers',
    hairColor: 'BlondeGolden',
    hatColor: 'PastelYellow',
    facialHairType: 'BeardMajestic',
    facialHairColor: 'Red',
    clotheType: 'BlazerShirt',
    clotheColor: 'PastelYellow',
    graphicType: 'Pizza',
    eyeType: 'Dizzy',
    eyebrowType: 'AngryNatural',
    mouthType: 'Eating',
    skinColor: 'Brown',
  },
  {
    id: 'avatar-29',
    backdropType: 'None',
    backdropColor: 'Red',
    topType: 'ShortHairShaggyMullet',
    accessoriesType: 'Blank',
    hairColor: 'Brown',
    hatColor: 'Pink',
    facialHairType: 'MoustacheFancy',
    facialHairColor: 'SilverGray',
    clotheType: 'BlazerSweater',
    clotheColor: 'Pink',
    graphicType: 'Resist',
    eyeType: 'EyeRoll',
    eyebrowType: 'Default',
    mouthType: 'Grimace',
    skinColor: 'DarkBrown',
  },
  {
    id: 'avatar-30',
    backdropType: 'None',
    backdropColor: 'White',
    topType: 'ShortHairShortCurly',
    accessoriesType: 'Kurt',
    hairColor: 'BrownDark',
    hatColor: 'Red',
    facialHairType: 'MoustacheMagnum',
    facialHairColor: 'CustomFacialHairTeal',
    clotheType: 'CollarSweater',
    clotheColor: 'Red',
    graphicType: 'Selena',
    eyeType: 'Happy',
    eyebrowType: 'DefaultNatural',
    mouthType: 'Sad',
    skinColor: 'Black',
  },
  {
    id: 'avatar-31',
    backdropType: 'None',
    backdropColor: 'CustomBackdropGreen',
    topType: 'ShortHairShortFlat',
    accessoriesType: 'Prescription01',
    hairColor: 'PastelPink',
    hatColor: 'White',
    facialHairType: 'Blank',
    facialHairColor: 'Auburn',
    clotheType: 'GraphicShirt',
    clotheColor: 'White',
    graphicType: 'Bear',
    eyeType: 'Hearts',
    eyebrowType: 'FlatNatural',
    mouthType: 'ScreamOpen',
    skinColor: 'Tanned',
  },
  {
    id: 'avatar-32',
    backdropType: 'None',
    backdropColor: 'CustomBackdropGreen',
    topType: 'ShortHairShortRound',
    accessoriesType: 'Prescription02',
    hairColor: 'Blue',
    hatColor: 'CustomHatLime',
    facialHairType: 'BeardMedium',
    facialHairColor: 'Black',
    clotheType: 'Hoodie',
    clotheColor: 'CustomClotheOrange',
    graphicType: 'SkullOutline',
    eyeType: 'Side',
    eyebrowType: 'FrownNatural',
    mouthType: 'Serious',
    skinColor: 'Yellow',
  },
]
